### ISSUE TITLE
Fresh install on full VM does not present working play for weblets environment

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#1136]
Version if the software installed:
```
root@playweb`lets:~/code/ThreeFoldTech/grid_weblets# node -v
v16.9.1
root@playweblets:~/code/ThreeFoldTech/grid_weblets# npm -v
7.21.1
root@playweblets:~/code/ThreeFoldTech/grid_weblets# yarn -v
1.22.19
root@playweblets:~/code/ThreeFoldTech/grid_weblets# uname -a
Linux playweblets 5.15.0-1002-kvm #2-Ubuntu SMP Wed Feb 9 10:14:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@playweblets:~/code/ThreeFoldTech/grid_weblets#
```

According to the README:
``` yarn deps``` completes successful:
```
root@playweblets:~/code/ThreeFoldTech/grid_weblets# yarn deps

yarn run v1.22.19
$ sh scripts/install_deps.sh
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @polkadot/extension-dapp@0.41.2" has unmet peer dependency "@polkadot/util@*".
warning " > @polkadot/extension-dapp@0.41.2" has unmet peer dependency "@polkadot/util-crypto@*".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util@9.7.2".
warning "grid3_client 


> ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util-crypto@9.7.2".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util@6.11.1".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util-crypto@6.11.1".
warning " > autoprefixer@10.4.12" has unmet peer dependency "postcss@^8.1.0".
warning " > eslint-config-standard-with-typescript@23.0.0" has incorrect peer dependency "eslint@^8.0.1".
warning "eslint-config-standard-with-typescript > eslint-config-standard@17.0.0" has incorrect peer dependency "eslint@^8.0.1".
warning " > eslint-plugin-svelte3@4.0.0" has incorrect peer dependency "eslint@>=8.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.6.2" has unmet peer dependency "@polkadot/util@9.6.2".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.6.2" has unmet peer dependency "@polkadot/util-crypto@9.6.2".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util@6.11.1".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util-crypto@6.11.1".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 297.48s.
root@playweblets:~/code/ThreeFoldTech/grid_weblets#
```

The `yarn server:app` fails as follows:
```
root@playweblets:~/code/ThreeFoldTech/grid_weblets# yarn serve:app
yarn run v1.22.19
$ yarn build && sh scripts/build.sh && cd playground && yarn serve
$ rollup -c

src/elements/ContractsList/index.ts → .build/build/elements/contractslist.wc.js...
created .build/build/elements/contractslist.wc.js in 12.2s

src/elements/DeployedList/index.ts → .build/build/elements/deployedlist.wc.js...
created .build/build/elements/deployedlist.wc.js in 13s

src/elements/FarmingCalculator/index.ts → .build/build/elements/farmingcalculator.wc.js...
created .build/build/elements/farmingcalculator.wc.js in 10.2s

src/elements/Import/index.ts → .build/build/elements/import.wc.js...
created .build/build/elements/import.wc.js in 5.6s

src/elements/Mastodon/index.ts → .build/build/elements/mastodon.wc.js...
created .build/build/elements/mastodon.wc.js in 9.1s

src/elements/Mattermost/index.ts → .build/build/elements/mattermost.wc.js...
created .build/build/elements/mattermost.wc.js in 10.5s

src/elements/Notification/index.ts → .build/build/elements/notification.wc.js...
created .build/build/elements/notification.wc.js in 4s

src/elements/TFhubValidator/index.ts → .build/build/elements/tfhubvalidator.wc.js...
created .build/build/elements/tfhubvalidator.wc.js in 8.6s

src/elements/algorand/index.ts → .build/build/elements/algorand.wc.js...
created .build/build/elements/algorand.wc.js in 9.3s

src/elements/base/index.ts → .build/build/elements/base.wc.js...
created .build/build/elements/base.wc.js in 7s

src/elements/caprover/index.ts → .build/build/elements/caprover.wc.js...
created .build/build/elements/caprover.wc.js in 9.3s

src/elements/casperlabs/index.ts → .build/build/elements/casperlabs.wc.js...
created .build/build/elements/casperlabs.wc.js in 8.8s

src/elements/disclaimer/index.ts → .build/build/elements/disclaimer.wc.js...
created .build/build/elements/disclaimer.wc.js in 6.7s

src/elements/discourse/index.ts → .build/build/elements/discourse.wc.js...
created .build/build/elements/discourse.wc.js in 10.3s

src/elements/fullvm/index.ts → .build/build/elements/fullvm.wc.js...
created .build/build/elements/fullvm.wc.js in 9.3s

src/elements/funkwhale/index.ts → .build/build/elements/funkwhale.wc.js...
created .build/build/elements/funkwhale.wc.js in 9.3s

src/elements/inca/index.ts → .build/build/elements/inca.wc.js...
created .build/build/elements/inca.wc.js in 3.7s

src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
created .build/build/elements/kubernetes.wc.js in 9.2s

src/elements/nodePilot/index.ts → .build/build/elements/nodepilot.wc.js...
created .build/build/elements/nodepilot.wc.js in 9s

src/elements/owncloud/index.ts → .build/build/elements/owncloud.wc.js...
created .build/build/elements/owncloud.wc.js in 13.5s

src/elements/peertube/index.ts → .build/build/elements/peertube.wc.js...
created .build/build/elements/peertube.wc.js in 9.2s

src/elements/presearch/index.ts → .build/build/elements/presearch.wc.js...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@playweblets:~/code/ThreeFoldTech/grid_weblets#
```

Not sure what I am doing wrong...

**Comment by zaelgohary** [comment]
the error in the logs will be removed if you exported openssl-legacy-provider in node options. This can be done by:
export NODE_OPTIONS="--max-old-space-size=8192 --openssl-legacy-provider"

**Comment by weynandkuijpers** [comment]
I think I did this:
```
root@playgrid:~/code/github/grid_weblets# env | grep -i node
NODE_OPTIONS=--max-old-space-size=8192
root@playgrid:~/code/github/grid_weblets# export NODE_OPTIONS="--max-old-space-size=8192 --openssl-legacy-provider"
root@playgrid:~/code/github/grid_weblets# env | grep -i node
NODE_OPTIONS=--max-old-space-size=8192 --openssl-legacy-provider
```
... and it provided me with an error:
```
root@playgrid:~/code/github/grid_weblets# yarn deps
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
root@playgrid:~/code/github/grid_weblets#
```

Version:
```
root@playgrid:~/code/github/grid_weblets# yarn --version
1.22.19
root@playgrid:~/code/github/grid_weblets# npm --v
8.19.2
root@playgrid:~/code/github/grid_weblets# node -v
v16.18.1
root@playgrid:~/code/github/grid_weblets#
```

So do I need another node version?  I took the information provided here: https://github.com/threefoldtech/grid_weblets/blob/development/docs/config.md

Does it perse need to be version 16.0.0?

**Comment by weynandkuijpers** [comment]
Uninstalled version 16.8, installed latest version 19.1.0

```
root@playgrid:~/code/github/grid_weblets# node -v
v19.1.0
```
this results is more errors...
```
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/root/code/github/grid_weblets/playground/node_modules/sodium-native/build'
  CXX(target) Release/obj.target/sodium/binding.o
In file included from ../../nan/nan.h:178,
                 from ../binding.cc:3:
../../nan/nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                       ^~~~~~~~~~~~~~~~~
../../nan/nan_callbacks.h:55:40: error: template argument 1 is invalid
   55 | typedef v8::Local<v8::AccessorSignature> Sig;
      |                                        ^
In file included from ../binding.cc:3:
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:2544:19: error: no matching function for call to ‘v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&, Nan::imp::Sig&)’
 2544 |   tpl->SetAccessor(
      |   ~~~~~~~~~~~~~~~~^
 2545 |       name
      |       ~~~~
 2546 |     , getter_
      |     ~~~~~~~~~
 2547 |     , setter_
      |     ~~~~~~~~~
 2548 |     , obj
      |     ~~~~~
 2549 |     , settings
      |     ~~~~~~~~~~
 2550 |     , attribute
      |     ~~~~~~~~~~~
 2551 |     , signature);
      |     ~~~~~~~~~~~~
In file included from /root/.cache/node-gyp/19.1.0/include/node/v8-function.h:15,
                 from /root/.cache/node-gyp/19.1.0/include/node/v8.h:33,
                 from /root/.cache/node-gyp/19.1.0/include/node/node.h:73,
                 from ../binding.cc:1:
/root/.cache/node-gyp/19.1.0/include/node/v8-template.h:807:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  807 |   void SetAccessor(
      |        ^~~~~~~~~~~
/root/.cache/node-gyp/19.1.0/include/node/v8-template.h:812:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  812 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/19.1.0/include/node/v8-template.h:814:8: note: candidate: ‘void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)’
  814 |   void SetAccessor(
      |        ^~~~~~~~~~~
/root/.cache/node-gyp/19.1.0/include/node/v8-template.h:819:22: note:   no known conversion for argument 7 from ‘Nan::imp::Sig’ {aka ‘int’} to ‘v8::SideEffectType’
  819 |       SideEffectType getter_side_effect_type = SideEffectType::kHasSideEffect,
      |       ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/crypto_pwhash_async.cc:2,
                 from ../binding.cc:12:
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_malloc(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  102 |   if (((uint64_t) var) < min) { \\\n../binding.cc:49:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   49 |   ASSERT_UINT_BOUNDS(info[0], size, 0, 0, `buffer.constants.MAX_LENGTH`, node::Buffer::kMaxLength)
      |   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE randombytes_uniform(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  102 |   if (((uint64_t) var) < min) { \\\n../binding.cc:95:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
   95 |   ASSERT_UINT_BOUNDS(info[0], upper_bound, 0, 0, 0xffffffff, 0xffffffff)
      |   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_pad(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  102 |   if (((uint64_t) var) < min) { \\\n../binding.cc:157:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
  157 |   ASSERT_UINT_BOUNDS(info[1], unpadded_buflen, 0, 0, `buf.length`, buf_length)
      |   ^~~~~~~~~~~~~~~~~~
../binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sodium_unpad(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/macros.h:102:24: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
  102 |   if (((uint64_t) var) < min) { \\\n../binding.cc:169:3: note: in expansion of macro ‘ASSERT_UINT_BOUNDS’
  169 |   ASSERT_UINT_BOUNDS(info[1], padded_buflen, 0, 0, `buf.length`, buf_length)
      |   ^~~~~~~~~~~~~~~~~~
In file included from ../binding.cc:1:
../binding.cc: At global scope:
/root/.cache/node-gyp/19.1.0/include/node/node.h:993:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  993 |       (node::addon_register_func) (regfunc),                          \\\n      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/19.1.0/include/node/node.h:1027:3: note: in expansion of macro ‘NODE_MODULE_X’
 1027 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../binding.cc:1593:1: note: in expansion of macro ‘NODE_MODULE’
 1593 | NODE_MODULE(sodium, InitAll)
      | ^~~~~~~~~~~
make: *** [sodium.target.mk:132: Release/obj.target/sodium/binding.o] Error 1
make: Leaving directory '/root/code/github/grid_weblets/playground/node_modules/sodium-native/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Linux 5.15.0-1021-kvm
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /root/code/github/grid_weblets/playground/node_modules/sodium-native
Done in 215.34s.
root@playgrid:~/code/github/grid_weblets#
```

**Comment by A-Harby** [comment]
> ... and it provided me with an error:
> 
> ```
> root@playgrid:~/code/github/grid_weblets# yarn deps
> node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
> root@playgrid:~/code/github/grid_weblets#
> ```

@weynandkuijpers I faced a similar errors and the solution for me was `export NODE_OPTIONS="--max-old-space-size=8192"`, also node version was v16 like what u had before (cause latset version v19 wasn't working for me).

> Version:
> 
> ```
> root@playgrid:~/code/github/grid_weblets# yarn --version
> 1.22.19
> root@playgrid:~/code/github/grid_weblets# npm --v
> 8.19.2
> root@playgrid:~/code/github/grid_weblets# node -v
> v16.18.1
> root@playgrid:~/code/github/grid_weblets#
> ```

**Comment by mohamedamer453** [comment]
I followed the exact steps from https://github.com/threefoldtech/grid_weblets/blob/development/docs/config.md in a freshly installed full vm and it also did not work for me.

### Environment 

- Freshly installed Full VM with Ubuntu 22.04
- Node v18.12.1 (latest LTS)
- NPM 8.19.2
- Yarn v1.22.19

### Followed Steps
- Deployed a Full VM with Ubuntu 22.04 on qanet.
- Installed Node v18.12.1 through NVM
   ```
   root@testWeblets2:~/weblets/grid_weblets# node -v
   v18.12.1
   root@testWeblets2:~/weblets/grid_weblets# npm -v
   8.19.2
   root@testWeblets2:~/weblets/grid_weblets# yarn -v
   1.22.19
   ```
- Followed the rest of the steps from [config docs](https://github.com/threefoldtech/grid_weblets/blob/development/docs/config.md) 
- Also used `export NODE_OPTIONS="--max-old-space-size=8192 --openssl-legacy-provider"` since i was using Node 18
- Cloned the weblets repo.
- Installed the dependencies using `yarn deps` and it finished without any errors.
- Tried to build and serve the app using `yarn serve:app` but it failed in the end with the following error:
   ```
   src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
   Killed
   error Command failed with exit code 137.
   info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
   error Command failed with exit code 137.
   info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

   ```
### Full logs from running `yarn deps` & `yarn serve:app`

```bash
root@testWeblets2:~/weblets/grid_weblets# yarn deps
yarn run v1.22.19
$ sh scripts/install_deps.sh
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @polkadot/extension-dapp@0.41.2" has unmet peer dependency "@polkadot/util@*".
warning " > @polkadot/extension-dapp@0.41.2" has unmet peer dependency "@polkadot/util-crypto@*".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util@9.7.2".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.7.2" has unmet peer dependency "@polkadot/util-crypto@9.7.2".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util@6.11.1".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util-crypto@6.11.1".
warning " > autoprefixer@10.4.12" has unmet peer dependency "postcss@^8.1.0".
warning " > eslint-config-standard-with-typescript@23.0.0" has incorrect peer dependency "eslint@^8.0.1".
warning "eslint-config-standard-with-typescript > eslint-config-standard@17.0.0" has incorrect peer dependency "eslint@^8.0.1".
warning " > eslint-plugin-svelte3@4.0.0" has incorrect peer dependency "eslint@>=8.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
[4/4] Building fresh packages...
$ husky install
husky - Git hooks installed
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.6.2" has unmet peer dependency "@polkadot/util@9.6.2".
warning "grid3_client > ts-rmb-http-client > @polkadot/keyring@9.6.2" has unmet peer dependency "@polkadot/util-crypto@9.6.2".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util@6.11.1".
warning "ts-rmb-http-client > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util-crypto@6.11.1".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 660.87s.
root@testWeblets2:~/weblets/grid_weblets# yarn serve:app
yarn run v1.22.19
$ yarn build && sh scripts/build.sh && cd playground && yarn serve
$ rollup -c

src/elements/ContractsList/index.ts → .build/build/elements/contractslist.wc.js...
created .build/build/elements/contractslist.wc.js in 22.2s

src/elements/DeployedList/index.ts → .build/build/elements/deployedlist.wc.js...
created .build/build/elements/deployedlist.wc.js in 20s

src/elements/FarmingCalculator/index.ts → .build/build/elements/farmingcalculator.wc.js...
created .build/build/elements/farmingcalculator.wc.js in 16.2s

src/elements/Import/index.ts → .build/build/elements/import.wc.js...
created .build/build/elements/import.wc.js in 8.9s

src/elements/Mastodon/index.ts → .build/build/elements/mastodon.wc.js...
created .build/build/elements/mastodon.wc.js in 14.9s

src/elements/Mattermost/index.ts → .build/build/elements/mattermost.wc.js...
created .build/build/elements/mattermost.wc.js in 14.5s

src/elements/Notification/index.ts → .build/build/elements/notification.wc.js...
created .build/build/elements/notification.wc.js in 6.9s

src/elements/TFhubValidator/index.ts → .build/build/elements/tfhubvalidator.wc.js...
created .build/build/elements/tfhubvalidator.wc.js in 14.3s

src/elements/algorand/index.ts → .build/build/elements/algorand.wc.js...
created .build/build/elements/algorand.wc.js in 14.7s

src/elements/base/index.ts → .build/build/elements/base.wc.js...
created .build/build/elements/base.wc.js in 11s

src/elements/caprover/index.ts → .build/build/elements/caprover.wc.js...
created .build/build/elements/caprover.wc.js in 14.7s

src/elements/casperlabs/index.ts → .build/build/elements/casperlabs.wc.js...
created .build/build/elements/casperlabs.wc.js in 13.9s

src/elements/disclaimer/index.ts → .build/build/elements/disclaimer.wc.js...
created .build/build/elements/disclaimer.wc.js in 6.7s

src/elements/discourse/index.ts → .build/build/elements/discourse.wc.js...
created .build/build/elements/discourse.wc.js in 16.6s

src/elements/fullvm/index.ts → .build/build/elements/fullvm.wc.js...
created .build/build/elements/fullvm.wc.js in 15.3s

src/elements/funkwhale/index.ts → .build/build/elements/funkwhale.wc.js...
created .build/build/elements/funkwhale.wc.js in 15.2s

src/elements/inca/index.ts → .build/build/elements/inca.wc.js...
created .build/build/elements/inca.wc.js in 6.9s

src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
### Using `TARGET_WEBLETS`

it also did not work when i build only a couple of weblets using the `TARGET_WEBLETS` env var.

```bash
root@testWeblets2:~/weblets/grid_weblets# export TARGET_WEBLETS="vm peertube deployedList profile"
root@testWeblets2:~/weblets/grid_weblets# yarn serve:app
yarn run v1.22.19
$ yarn build && sh scripts/build.sh && cd playground && yarn serve
$ rollup -c

src/elements/vm/index.ts → .build/build/elements/vm.wc.js...
created .build/build/elements/vm.wc.js in 22.4s

src/elements/peertube/index.ts → .build/build/elements/peertube.wc.js...
created .build/build/elements/peertube.wc.js in 15.9s

src/elements/deployedList/index.ts → .build/build/elements/deployedlist.wc.js...
[!] Error: Could not resolve entry module (src/elements/deployedList/index.ts).
Error: Could not resolve entry module (src/elements/deployedList/index.ts).
    at error (/root/weblets/grid_weblets/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/root/weblets/grid_weblets/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zaelgohary** [comment]
@mohamedamer453 You'll need to run .bashrc file if you added NODE_OPTIONS in it. So it would be as follows:
```bash
echo "export NODE_OPTIONS='--max-old-space-size=8192 --openssl-legacy-provider'" >> ~/.bashrc
source ~/.bashrc
```

Also, make sure to install libtool, libtool-bin, and node-gyp using these commands: 
```bash
sud apt update
sudo apt install autoconf automake g++ libtool libtool-bin
sudo npm install -g node-gyp
```

**Comment by mohamedamer453** [comment]
Verified.

I tried the flow again on a new vm with the new steps added in https://github.com/threefoldtech/grid_weblets/pull/1165/files and it solved the build issue and the other issues i faced while installing the dependencies.

and the build was complete without any issues with the same versions mentioned above
```bash
root@VM07a781cc5:~/grid_weblets# yarn serve:app
yarn run v1.22.19
$ yarn build && sh scripts/build.sh && cd playground && yarn serve
$ rollup -c

src/elements/ContractsList/index.ts → .build/build/elements/contractslist.wc.js...
created .build/build/elements/contractslist.wc.js in 16.8s

src/elements/DeployedList/index.ts → .build/build/elements/deployedlist.wc.js...
created .build/build/elements/deployedlist.wc.js in 20.5s

src/elements/FarmingCalculator/index.ts → .build/build/elements/farmingcalculator.wc.js...
created .build/build/elements/farmingcalculator.wc.js in 16.6s

src/elements/Import/index.ts → .build/build/elements/import.wc.js...
created .build/build/elements/import.wc.js in 9.1s

src/elements/Mastodon/index.ts → .build/build/elements/mastodon.wc.js...
created .build/build/elements/mastodon.wc.js in 15.9s

src/elements/Mattermost/index.ts → .build/build/elements/mattermost.wc.js...
created .build/build/elements/mattermost.wc.js in 15.3s

src/elements/Notification/index.ts → .build/build/elements/notification.wc.js...
created .build/build/elements/notification.wc.js in 6.8s

src/elements/TFhubValidator/index.ts → .build/build/elements/tfhubvalidator.wc.js...
created .build/build/elements/tfhubvalidator.wc.js in 15.2s

src/elements/algorand/index.ts → .build/build/elements/algorand.wc.js...
created .build/build/elements/algorand.wc.js in 14.4s

src/elements/base/index.ts → .build/build/elements/base.wc.js...
created .build/build/elements/base.wc.js in 11s

src/elements/caprover/index.ts → .build/build/elements/caprover.wc.js...
created .build/build/elements/caprover.wc.js in 17.5s

src/elements/casperlabs/index.ts → .build/build/elements/casperlabs.wc.js...
created .build/build/elements/casperlabs.wc.js in 15.7s

src/elements/disclaimer/index.ts → .build/build/elements/disclaimer.wc.js...
created .build/build/elements/disclaimer.wc.js in 7s

src/elements/discourse/index.ts → .build/build/elements/discourse.wc.js...
created .build/build/elements/discourse.wc.js in 16.7s

src/elements/fullvm/index.ts → .build/build/elements/fullvm.wc.js...
created .build/build/elements/fullvm.wc.js in 15s

src/elements/funkwhale/index.ts → .build/build/elements/funkwhale.wc.js...
created .build/build/elements/funkwhale.wc.js in 14.8s

src/elements/inca/index.ts → .build/build/elements/inca.wc.js...
created .build/build/elements/inca.wc.js in 7.1s

src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
created .build/build/elements/kubernetes.wc.js in 15.2s

src/elements/nodePilot/index.ts → .build/build/elements/nodepilot.wc.js...
created .build/build/elements/nodepilot.wc.js in 15.9s

src/elements/owncloud/index.ts → .build/build/elements/owncloud.wc.js...
created .build/build/elements/owncloud.wc.js in 17s

src/elements/peertube/index.ts → .build/build/elements/peertube.wc.js...
created .build/build/elements/peertube.wc.js in 16s

src/elements/presearch/index.ts → .build/build/elements/presearch.wc.js...
created .build/build/elements/presearch.wc.js in 14.9s

src/elements/profiles/index.ts → .build/build/elements/profiles.wc.js...
created .build/build/elements/profiles.wc.js in 12.4s

src/elements/qvm/index.ts → .build/build/elements/qvm.wc.js...
created .build/build/elements/qvm.wc.js in 15.7s

src/elements/subsquid/index.ts → .build/build/elements/subsquid.wc.js...
created .build/build/elements/subsquid.wc.js in 15.4s

src/elements/taiga/index.ts → .build/build/elements/taiga.wc.js...
created .build/build/elements/taiga.wc.js in 15.9s

src/elements/version/index.ts → .build/build/elements/version.wc.js...
created .build/build/elements/version.wc.js in 7.6s

src/elements/vm/index.ts → .build/build/elements/vm.wc.js...
created .build/build/elements/vm.wc.js in 19.7s
/root/grid_weblets
$ vue-cli-service serve
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
98% after emitting CopyPlugin

 WARNING  Compiled with 3 warnings                               11:12:32 AM

Module Warning (from ./node_modules/eslint-loader/index.js):

/root/grid_weblets/playground/src/App.vue
  23:8   warning  'api' is defined but never used           @typescript-eslint/no-unused-vars
  63:3   warning  Missing return type on function           @typescript-eslint/explicit-module-boundary-types
  71:3   warning  Missing return type on function           @typescript-eslint/explicit-module-boundary-types
  76:41  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 4 problems (0 errors, 4 warnings)


Module Warning (from ./node_modules/eslint-loader/index.js):

/root/grid_weblets/playground/src/configs.ts
  6:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  6:38  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  7:12  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  8:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 4 problems (0 errors, 4 warnings)


Module Warning (from ./node_modules/eslint-loader/index.js):

/root/grid_weblets/playground/src/views/Editor.vue
  225:3  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

✖ 1 problem (0 errors, 1 warning)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
No type errors found
Version: typescript 4.1.6
Time: 5710ms

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.20.2.2:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

```
