### ISSUE TITLE
Deploying the grid_weblets in a grid VM fails. I havew a community call tomorrow to showcase this!

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#1139]
I am trying to deploy the "play.grid.tf" in a grid-based full VM and it does not compile.

- followed the instructions as per the repo instructions
- then did the `yarn deps`
- then did the `yarn server:app --host <IP-address>`

Error:
```

src/elements/inca/index.ts → .build/build/elements/inca.wc.js...
created .build/build/elements/inca.wc.js in 3.1s

src/elements/kubernetes/index.ts → .build/build/elements/kubernetes.wc.js...
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@playgrid:~/code/github/grid_weblets# 
```

and then when I take Kubernetes out with the env environment:
```
export TARGET_WEBLETS="vm peertube deployedList profile"
```
Then starting the app again results in error:
```
root@playgrid:~/code/github/grid_weblets# export TARGET_WEBLETS="vm peertube deployedList profile"
root@playgrid:~/code/github/grid_weblets# yarn serve:app --host 45.156.243.209
yarn run v1.22.19
$ yarn build && sh scripts/build.sh && cd playground && yarn serve --host 45.156.243.209
$ rollup -c

src/elements/vm/index.ts → .build/build/elements/vm.wc.js...
created .build/build/elements/vm.wc.js in 12.8s

src/elements/peertube/index.ts → .build/build/elements/peertube.wc.js...
created .build/build/elements/peertube.wc.js in 9.2s

src/elements/deployedList/index.ts → .build/build/elements/deployedlist.wc.js...
[!] Error: Could not resolve entry module (src/elements/deployedList/index.ts).
Error: Could not resolve entry module (src/elements/deployedList/index.ts).
    at error (/root/code/github/grid_weblets/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/root/code/github/grid_weblets/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@playgrid:~/code/github/grid_weblets# 
```

**Comment by mohamedamer453** [comment]
I've also encountered the same issue when i tried the `TARGET_WEBLETS` option and it failed with the same error as seen in https://github.com/threefoldtech/grid_weblets/issues/1136#issuecomment-1336433044 so i'll close this issue and it'll be followed in the original issue #1136
