### ISSUE TITLE
dev playground - listed contracts doesnt react anymore after deleting one.

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/grid_weblets#1250]
I deleted I think only deployment 15613. But after it said success, it was still here, so I reloaded the page. now I cant delete any resource with following error.

deleting cache and cookies didnt workout

![image](https://user-images.githubusercontent.com/24993288/207114696-58891d03-0f9a-4b9f-ada7-af13b0e71014.png)

```
validator.js:21 Validation succeed
client.js:63 Executing method: getContractByID with args: 15614
contractslist.wc.js:9 Deployment Error TypeError: Cannot read properties of null (reading 'contractType')
    at f.<anonymous> (nodes.js:60:18)
    at Generator.next (<anonymous>)
    at a (nodes.js:4:58)
client.js:63 Executing method: getTwinIdByAccountId with args: 5H9G7P5bqB6NyftCHzs4sxDykdtc8AZodGoUnXZ6h3QnNPw3
validator.js:21 Validation succeed
client.js:63 Executing method: getBalanceOf with args: 5H9G7P5bqB6NyftCHzs4sxDykdtc8AZodGoUnXZ6h3QnNPw3
client.js:63 Executing method: getContractByID with args: 15613
contractslist.wc.js:9 Error TypeError: Cannot read properties of null (reading 'state')
    at c.<anonymous> (contracts.js:46:38)
    at Generator.next (<anonymous>)
    at a (contracts.js:4:58)
client.js:63 Executing method: getTwinIdByAccountId with args: 5H9G7P5bqB6NyftCHzs4sxDykdtc8AZodGoUnXZ6h3QnNPw3
10validator.js:21 Validation succeed
```

Also if I hit show details I get another error and the infos dont open:

```
Validation succeed
client.js:63 Executing method: getContractByID with args: 15613
contractslist.wc.js:9 Deployment Error TypeError: Cannot read properties of null (reading 'contractType')
    at f.<anonymous> (nodes.js:60:18)
    at Generator.next (<anonymous>)
    at a (nodes.js:4:58)
```

**Comment by zaelgohary** [comment]
I tried to reproduce the issue multiple times but couldn't.

**Comment by A-Harby** [comment]
Also couldn't reproduce issue through deleting one or many contracts in different scenarios.
Could be related to this [issue](https://github.com/threefoldtech/grid_weblets/issues/1196) and it was fixed.
