### ISSUE TITLE
Presearch: capacity filter doesn't work when Planetary Network is active.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#756]
### Description

The capacity filter in the presearch weblet doesn't work when the `Planetary Network` is the only option selected.

![image](https://user-images.githubusercontent.com/101194226/170877074-5e283980-f79c-498b-8d38-2ec92e2e0f7d.png)

with this error in the console 

```
Failed to load resource: the server responded with a status of 400 ()

Error findNodes Error: Request failed with status code 400
    at e.exports (createError.js:16:15)
    at e.exports (settle.js:17:12)
    at XMLHttpRequest.j (xhr.js:66:7)
```

![image](https://user-images.githubusercontent.com/101194226/170877169-579d385d-e22c-4f16-81cd-299f5140afaa.png)

however the Capacity filter works when the `Public IP` is also selected or when it's the only option selected

![image](https://user-images.githubusercontent.com/101194226/170877256-a057d55d-fe29-4b2a-8661-ab17163b6d19.png)

![image](https://user-images.githubusercontent.com/101194226/170877288-c9f4f532-d4db-49f1-b9a7-c209ea4dec17.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The capacity filter now works when `Planetary Network` is the only option selected.
with no errors in the console.

![image](https://user-images.githubusercontent.com/101194226/173609278-780644a4-8826-404f-8a44-dc82975bf078.png)


But when `Planetary Network` is the only option selected only `1` node is found for deployment 

![image](https://user-images.githubusercontent.com/101194226/173617163-28674f04-4d08-413d-8a80-f4d25c2f7ca2.png)

and when `Public IP` is the only option selected or selected with the `Planetary Network` option more nodes are found and are ready for deployment.

![image](https://user-images.githubusercontent.com/101194226/173617481-6773b0d7-eaa4-4ae2-ba17-99208018a2ef.png)

is this a normal occurrence for the capacity filter to have more nodes when `Public IP` filter is activated  and only `1` node when it's not activated?

**Comment by mohamedamer453** [comment]
Verified.
The original issue was verified here

> Verified on devnet.
> 
> The capacity filter now works when `Planetary Network` is the only option selected. with no errors in the console.
> 
> ![image](https://user-images.githubusercontent.com/101194226/173609278-780644a4-8826-404f-8a44-dc82975bf078.png)


and according to this 

> yes. this is the expected.
> 
> to be clearer. the capacity filter has a special way to filter nodes for presearch. as a presearch node itself needs to be accessible through a unique public IP. so if you choose to assign a public IP to your node you will have multiple options (each node belongs to a farm that has a free public IP). if not and you just apply the planetary IP the node will be accessible through the public IP of the farm it self and to not have two pre node has the same IP address ( if they are in the same farm ) the capacity filter drops all the nodes in this farm.
> 
> in your testing case. we have a pre node on node 15 (without public IP) which belongs to farm 1 so there is no nodes available without public Ip in this farm. just node 18 which belongs to farm 2.

the other mentioned issue appears to be a normal occurrence in case of presearch
